// @vitest-environment jsdom
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";

import type { GitCommitNode, GitFileChange, GitRef } from "../../src/types";
import { UNCOMMITTED_CHANGES_HASH } from "../../src/types";
import { vscode } from "../../web/utils";

/*
 * Keyboard integration of web/main.ts with the real Dropdown, context menu, dialogs, FindWidget,
 * FileHistoryController, RefOverflowController, BranchCleanupPanel and Graph. Only the host API
 * (postMessage) and the layout APIs jsdom lacks are controlled. Real Tab movement, native button
 * clicks from Enter / Space and IME are not generated by jsdom; those remain manual checks.
 */

/* ------------------------------------------------------------------ */
/* Constants and fixtures                                             */
/* ------------------------------------------------------------------ */

const REPO = "/test/repo";
const OTHER_REPO = "/test/other";
const FILE_PATH = "src/a.txt";
const STASH_HASH = "S";
const DIRECT_TITLE = "Direct parents and children";
const HIGHLIGHT_TITLE = "Highlight path";
const COPY_HASH_TITLE = "Copy Commit Hash to Clipboard";
const CLASS_ACTIVE = "active";
const CLASS_DROPDOWN_OPEN = "dropdownOpen";
const CLASS_DETAILS_OPEN = "commitDetailsOpen";
const CLASS_COMPARE_TARGET = "compareTarget";
const TAB_STOP = "0";
const PROGRAMMATIC_ONLY = "-1";
// Table layout stub: header 11px (+1 border) and 24px rows.
const HEADER_CLIENT_HEIGHT = 11;
const HEADER_HEIGHT = HEADER_CLIENT_HEIGHT + 1;
const ROW_HEIGHT = 24;

const ENGLISH_MESSAGES = JSON.parse(
  readFileSync(resolve(process.cwd(), "l10n/web/web.l10n.en.json"), "utf-8")
) as Record<string, string>;

const FILE_CHANGE: GitFileChange = {
  oldFilePath: FILE_PATH,
  newFilePath: FILE_PATH,
  type: "M",
  additions: 1,
  deletions: 1
};

function node(
  hash: string,
  parentHashes: string[],
  extra: Partial<GitCommitNode> = {}
): GitCommitNode {
  return {
    hash,
    parentHashes,
    author: "a",
    email: "e",
    date: 1700000000,
    message: `m ${hash}`,
    refs: [],
    stash: null,
    ...extra
  };
}

function ref(hash: string, name: string, type: GitRef["type"]): GitRef {
  return { hash, name, type };
}

/** N -> M -> R, HEAD = M, two branch labels on M. */
function standardCommits(): GitCommitNode[] {
  return [
    node("N", ["M"]),
    node("M", ["R"], { refs: [ref("M", "feature", "head"), ref("M", "hotfix", "head")] }),
    node("R", [])
  ];
}

/** Same rows with the two labels on R (Tab boundary cases). */
function labelsOnLastRowCommits(): GitCommitNode[] {
  return [
    node("N", ["M"]),
    node("M", ["R"]),
    node("R", [], { refs: [ref("R", "feature", "head"), ref("R", "hotfix", "head")] })
  ];
}

/** N -> M (merge of A and B) -> R. */
function mergeCommits(): GitCommitNode[] {
  return [
    node("N", ["M"]),
    node("M", ["A", "B"]),
    node("A", ["R"]),
    node("B", ["R"]),
    node("R", [])
  ];
}

function stashCommits(): GitCommitNode[] {
  return [
    node("N", ["M"]),
    node(STASH_HASH, ["M"], {
      message: "WIP on main",
      stash: { selector: "stash@{0}", baseHash: "M", untrackedFilesHash: null }
    }),
    node("M", ["R"]),
    node("R", [])
  ];
}

function uncommittedCommits(): GitCommitNode[] {
  return [
    node(UNCOMMITTED_CHANGES_HASH, ["M"], { message: "Uncommitted Changes (2)" }),
    ...standardCommits()
  ];
}

/* ------------------------------------------------------------------ */
/* Helpers                                                            */
/* ------------------------------------------------------------------ */

function dispatch(data: Record<string, unknown>): void {
  window.dispatchEvent(new MessageEvent("message", { data }));
}

function loadCommits(
  commits: GitCommitNode[],
  options: { head?: string | null; hard?: boolean; moreCommitsAvailable?: boolean } = {}
): void {
  dispatch({
    command: "loadCommits",
    commits,
    head: options.head === undefined ? "M" : options.head,
    moreCommitsAvailable: options.moreCommitsAvailable ?? false,
    hard: options.hard ?? true
  });
}

function loadBranches(): void {
  dispatch({
    command: "loadBranches",
    branches: ["feature", "hotfix"],
    head: "feature",
    hard: true,
    isRepo: true
  });
}

function loadRepos(repos: string[], lastActiveRepo = REPO): void {
  dispatch({
    command: "loadRepos",
    repos: Object.fromEntries(
      repos.map((repo) => [repo, { columnWidths: null, recentActions: [] }])
    ),
    lastActiveRepo
  });
}

function fire(target: Element | Document, type: string, init: MouseEventInit = {}): MouseEvent {
  const event = new MouseEvent(type, { bubbles: true, cancelable: true, ...init });
  target.dispatchEvent(event);
  return event;
}

interface KeyOptions extends KeyboardEventInit {
  readonly keyup?: boolean;
}

/** Dispatches keydown (and by default the matching keyup); returns the keydown event. */
function press(target: EventTarget, key: string, options: KeyOptions = {}): KeyboardEvent {
  const { keyup = true, ...init } = options;
  const keydown = new KeyboardEvent("keydown", { key, bubbles: true, cancelable: true, ...init });
  target.dispatchEvent(keydown);
  if (keyup) {
    target.dispatchEvent(
      new KeyboardEvent("keyup", { key, bubbles: true, cancelable: true, ...init })
    );
  }
  return keydown;
}

function pressEscape(target: EventTarget = document, init: KeyboardEventInit = {}): KeyboardEvent {
  return press(target, "Escape", { keyup: false, ...init });
}

function releaseEscape(target: EventTarget = document): void {
  target.dispatchEvent(
    new KeyboardEvent("keyup", { key: "Escape", bubbles: true, cancelable: true })
  );
}

function table(): HTMLElement {
  return document.getElementById("commitTable")!;
}

function row(hash: string): HTMLElement {
  const elem = Array.from(table().querySelectorAll<HTMLElement>("tr[data-hash]")).find(
    (candidate) => candidate.dataset.hash === hash
  );
  expect(elem, `row ${hash}`).toBeDefined();
  return elem!;
}

function rowsWithTabStop(): string[] {
  return Array.from(table().querySelectorAll<HTMLElement>('tr[data-hash][tabindex="0"]')).map(
    (elem) => elem.dataset.hash!
  );
}

function focusRow(hash: string): HTMLElement {
  const elem = row(hash);
  elem.focus();
  expect(document.activeElement).toBe(elem);
  return elem;
}

/** The operable ref buttons of a row (each `.gitRef` wrapper holds one per head / remote). */
function labelsOf(hash: string): HTMLElement[] {
  return Array.from(row(hash).querySelectorAll<HTMLElement>(".gitRef button.gitRefButton"));
}

function posts(command?: string): Record<string, unknown>[] {
  return vi
    .mocked(vscode.postMessage)
    .mock.calls.map((call) => call[0] as unknown as Record<string, unknown>)
    .filter((message) => command === undefined || message.command === command);
}

function clearPosts(): void {
  vi.mocked(vscode.postMessage).mockClear();
}

function details(): HTMLElement | null {
  return document.getElementById("commitDetails");
}

/** Hash of the row the details view follows, or null while no details are open. */
function detailsOwner(): string | null {
  const owner = details()?.previousElementSibling;
  return owner instanceof HTMLElement ? (owner.dataset.hash ?? null) : null;
}

function detailsOpenRows(): string[] {
  return Array.from(table().querySelectorAll<HTMLElement>(`tr.${CLASS_DETAILS_OPEN}`)).map(
    (elem) => elem.dataset.hash!
  );
}

function compareTargetRows(): string[] {
  return Array.from(table().querySelectorAll<HTMLElement>(`tr.${CLASS_COMPARE_TARGET}`)).map(
    (elem) => elem.dataset.hash!
  );
}

function respondDetails(hash: string, parents: string[] = [], fileChanges = [FILE_CHANGE]): void {
  dispatch({
    command: "commitDetails",
    commitDetails: {
      hash,
      parents,
      author: "a",
      email: "e",
      date: 0,
      committer: "",
      committerEmail: "",
      body: "",
      fileChanges
    }
  });
}

function openDetails(hash: string): void {
  fire(row(hash), "click");
  respondDetails(hash);
  expect(detailsOwner()).toBe(hash);
}

function startCompare(base: string, target: string): void {
  openDetails(base);
  fire(row(target), "click", { ctrlKey: true });
  dispatch({
    command: "compareCommits",
    fileChanges: [FILE_CHANGE],
    fromHash: target,
    toHash: base
  });
  expect(compareTargetRows()).toEqual([target]);
}

function dropdownTrigger(id: string): HTMLButtonElement {
  const trigger = document.querySelector<HTMLButtonElement>(`#${id} > .dropdownCurrentValue`);
  expect(trigger, `${id} trigger`).not.toBeNull();
  return trigger!;
}

function dropdownIsOpen(id: string): boolean {
  return document.getElementById(id)!.classList.contains(CLASS_DROPDOWN_OPEN);
}

function openDropdown(id: string): void {
  fire(dropdownTrigger(id), "click");
  expect(dropdownIsOpen(id)).toBe(true);
}

function contextMenuElem(): HTMLElement {
  return document.getElementById("contextMenu")!;
}

function menuIsActive(): boolean {
  return contextMenuElem().classList.contains(CLASS_ACTIVE);
}

function menuItem(title: string): HTMLElement {
  const item = Array.from(contextMenuElem().querySelectorAll<HTMLElement>("li")).find(
    (candidate) => candidate.textContent === title
  );
  expect(item, `menu item "${title}"`).toBeDefined();
  return item!;
}

function dialogIsActive(): boolean {
  return document.getElementById("dialog")!.classList.contains(CLASS_ACTIVE);
}

function findWidgetIsVisible(): boolean {
  return document.querySelector(".findWidget") !== null
    ? document.querySelector(".findWidget")!.classList.contains(CLASS_ACTIVE)
    : false;
}

function historyBar(): HTMLElement {
  return document.getElementById("fileHistoryBar")!;
}

function historyIsActive(): boolean {
  return historyBar().classList.contains(CLASS_ACTIVE);
}

function pathBar(): HTMLElement {
  return document.getElementById("pathHighlightBar")!;
}

function scrollContainer(): HTMLElement {
  return document.getElementById("scrollContainer")!;
}

function highlightThroughMenu(hash: string): void {
  fire(row(hash), "contextmenu");
  const parent = Array.from(
    document.querySelectorAll<HTMLElement>("#contextMenu li.contextMenuParent")
  ).find((item) => item.textContent?.startsWith(HIGHLIGHT_TITLE));
  expect(parent, HIGHLIGHT_TITLE).toBeDefined();
  const submenu = document.getElementById(`contextSubmenu_${parent!.dataset.submenuIndex}`)!;
  const item = Array.from(submenu.querySelectorAll<HTMLElement>("li")).find(
    (candidate) => candidate.textContent === DIRECT_TITLE
  );
  expect(item, DIRECT_TITLE).toBeDefined();
  fire(item!, "click");
  expect(pathBar().classList.contains(CLASS_ACTIVE)).toBe(true);
}

/** Opens M's details and requests the history of its file; `entries` are the matching hashes. */
function requestFileHistory(entries: string[] | null): void {
  openDetails("M");
  const icon = document.querySelector<HTMLElement>("#commitDetails .highlightFileHistory");
  expect(icon, "file history icon").not.toBeNull();
  const before = posts().length;
  fire(icon!, "click");
  const [request] = posts("fileHistory");
  expect(request, "fileHistory request").toBeDefined();
  expect(posts().length - before).toBe(1);
  if (entries === null) return;
  dispatch({
    command: "fileHistory",
    repo: REPO,
    requestId: request!.requestId,
    anchorHash: "M",
    filePath: FILE_PATH,
    entries: entries.map((hash) => ({
      hash,
      parentHashes: [],
      type: "M",
      oldFilePath: FILE_PATH,
      newFilePath: FILE_PATH,
      historicalPath: FILE_PATH,
      isMerge: false
    }))
  });
  expect(historyIsActive()).toBe(true);
}

/** Answers a hard refresh: the branch response (whose callback requests commits) and the commits. */
function respondToRefresh(commits: GitCommitNode[], head: string | null = "M"): void {
  loadBranches();
  clearPosts();
  loadCommits(commits, { head });
}

/** Closes every layer a previous case may have left open. */
function closeEverything(): void {
  if (menuIsActive()) fire(document, "click");
  if (dialogIsActive()) pressEscape();
  for (const id of ["repoSelect", "branchSelect", "authorSelect"]) {
    if (dropdownIsOpen(id)) pressEscape();
  }
  if (findWidgetIsVisible()) fire(document.getElementById("findClose")!, "click");
  if (details() !== null) fire(document.getElementById("commitDetailsClose")!, "click");
  if (historyIsActive()) fire(document.getElementById("fileHistoryExit")!, "click");
  if (details() !== null) fire(document.getElementById("commitDetailsClose")!, "click");
  if (pathBar().classList.contains(CLASS_ACTIVE)) {
    fire(document.getElementById("pathHighlightClear")!, "click");
  }
  const panel = document.getElementById("branchCleanupPanel")!;
  if (!panel.hasAttribute("hidden")) fire(document.getElementById("branchCleanupBtn")!, "click");
  for (const extra of Array.from(document.querySelectorAll(".keyboardTestExtra"))) extra.remove();
}

/* --- Modules loaded after the webview DOM exists (dialogs resolves #dialog on import) --- */

type DropdownClass = typeof import("../../web/dropdown").Dropdown;
type FileHistoryClass = typeof import("../../web/fileHistory").FileHistoryController;
type FindWidgetClass = typeof import("../../web/findWidget").FindWidget;
type GraphClass = typeof import("../../web/graph").Graph;

let Dropdown: DropdownClass;
let FileHistoryController: FileHistoryClass;
let FindWidget: FindWidgetClass;
let Graph: GraphClass;

/* ------------------------------------------------------------------ */
/* Boot                                                               */
/* ------------------------------------------------------------------ */

const clientHeightGetter = Object.getOwnPropertyDescriptor(Element.prototype, "clientHeight")!.get!;

beforeAll(async () => {
  document.body.innerHTML = [
    '<div id="controls">',
    '<span id="repoControl"><div id="repoSelect" class="dropdown"></div></span>',
    '<div id="branchSelect" class="dropdown"></div>',
    '<div id="authorSelect" class="dropdown"></div>',
    '<input type="checkbox" id="showRemoteBranchesCheckbox" value="1" checked>',
    '<button id="branchCleanupBtn" type="button"></button><button id="searchBtn" type="button"></button>',
    '<button id="fetchBtn" type="button"></button><button id="currentBtn" type="button"></button>',
    '<button id="refreshBtn" type="button"></button>',
    "</div>",
    '<div id="branchCleanupPanel" hidden></div>',
    '<div id="scrollContainer"><div id="scrollShadow"></div>',
    '<div id="content"><div id="commitGraph"></div><div id="commitTable"></div></div>',
    '<div id="footer"></div></div>',
    '<ul id="contextMenu"></ul><div id="dialogBacking"></div><div id="dialog"></div>'
  ].join("");
  (globalThis as Record<string, unknown>).viewState = {
    repos: {
      [REPO]: { columnWidths: null, recentActions: [] },
      [OTHER_REPO]: { columnWidths: null, recentActions: [] }
    },
    lastActiveRepo: REPO,
    dateFormat: "Date & Time",
    fetchAvatars: false,
    graphColours: ["#0085d9", "#d9534f"],
    graphStyle: "rounded",
    initialLoadCommits: 300,
    keybindings: { find: "f", refresh: "r", scrollToHead: "h", scrollToStash: "s" },
    loadMoreCommits: 100,
    loadMoreCommitsAutomatically: false,
    showCurrentBranchByDefault: false,
    showRecentActions: true,
    commitOrdering: "date",
    mute: { mergeCommits: false, commitsNotAncestorsOfHead: false },
    dialogDefaults: {
      merge: { noFastForward: true, squashCommits: false, noCommit: false },
      cherryPick: { recordOrigin: false, noCommit: false },
      stashUncommittedChanges: { includeUntracked: false },
      createWorktree: { openTerminal: true },
      removeWorktree: { deleteBranch: true }
    }
  };
  globalThis.webviewMessages = ENGLISH_MESSAGES;
  vi.stubGlobal(
    "ResizeObserver",
    class {
      observe(): void {}
      unobserve(): void {}
      disconnect(): void {}
    }
  );
  vi.spyOn(HTMLElement.prototype, "clientHeight", "get").mockImplementation(function (
    this: HTMLElement
  ) {
    if (this.id === "tableColHeaders") return HEADER_CLIENT_HEIGHT;
    if (this.tagName === "TABLE" && this.parentElement?.id === "commitTable") {
      return HEADER_HEIGHT + ROW_HEIGHT * this.querySelectorAll("tr.commit").length;
    }
    return clientHeightGetter.call(this);
  });

  await import("../../web/main");
  Dropdown = (await import("../../web/dropdown")).Dropdown;
  FileHistoryController = (await import("../../web/fileHistory")).FileHistoryController;
  FindWidget = (await import("../../web/findWidget")).FindWidget;
  Graph = (await import("../../web/graph")).Graph;
  loadBranches();
});

afterAll(() => {
  vi.restoreAllMocks();
});

beforeEach(() => {
  closeEverything();
  loadRepos([REPO, OTHER_REPO]);
  // The target survives same-repository updates by design, so each case starts from a switch.
  dispatch({ command: "selectRepo", repo: OTHER_REPO });
  respondToRefresh([], null);
  dispatch({ command: "selectRepo", repo: REPO });
  respondToRefresh(standardCommits());
  (document.activeElement as HTMLElement | null)?.blur();
  clearPosts();
});

afterEach(() => {
  vi.restoreAllMocks();
});

/* ------------------------------------------------------------------ */
/* S69: row target initialisation, maintenance and repository switch  */
/* ------------------------------------------------------------------ */

// @see docs/testing/perspectives/web/main-test/13-keyboard-accessibility-01.md
describe("row target initialisation, maintenance and repository switch (S69)", () => {
  it("gives the HEAD row real focus with tabindex 0 and no details request (TC-645)", () => {
    // Case: TC-645 (K07 / A8.1-1 main regression: pre-implementation activeElement stayed body)
    const elem = focusRow("M");
    expect(elem.getAttribute("tabindex")).toBe(TAB_STOP);
    expect(posts("commitDetails")).toEqual([]);
  });

  it("keeps the focus on the refresh button when the initial data arrives (TC-646)", () => {
    // Case: TC-646 (K01)
    const refreshBtn = document.getElementById("refreshBtn")!;
    refreshBtn.focus();
    clearPosts();

    loadCommits(standardCommits());

    expect(rowsWithTabStop()).toEqual(["M"]);
    expect(document.activeElement).toBe(refreshBtn);
    expect(posts()).toEqual([]);
  });

  it("makes the named list container the tab stop when zero rows are accepted (TC-647)", () => {
    // Case: TC-647 (K06 / A8.3-1); the accessible name is Task 9 / Task 11
    loadCommits([], { head: null });

    expect(rowsWithTabStop()).toEqual([]);
    expect(table().getAttribute("tabindex")).toBe(TAB_STOP);
    table().focus();
    expect(document.activeElement).toBe(table());
  });

  it("initialises to the HEAD of the new repository through selectRepo and the dropdown (TC-648)", () => {
    // Case: TC-648 (K02)
    focusRow("M");
    dispatch({ command: "selectRepo", repo: OTHER_REPO });
    clearPosts();
    respondToRefresh(standardCommits(), "R");
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(posts()).toEqual([]);

    // Back to the first repository through the real repo dropdown, then to the other one again
    openDropdown("repoSelect");
    const option = Array.from(
      document.querySelectorAll<HTMLElement>("#repoSelect .dropdownOption")
    ).find((candidate) => candidate.textContent?.includes("repo"));
    expect(option).toBeDefined();
    fire(option!, "click");
    expect(posts("loadBranches")).toHaveLength(1);
    respondToRefresh(standardCommits(), "N");
    expect(rowsWithTabStop()).toEqual(["N"]);
  });

  it("keeps the hash when the same repository is re-ordered (TC-649)", () => {
    // Case: TC-649 (K03)
    focusRow("M");
    loadCommits([node("R", []), node("M", ["R"]), node("N", ["M"])]);

    expect(rowsWithTabStop()).toEqual(["M"]);
    expect(row("M").dataset.id).toBe("1");
    expect(document.activeElement).toBe(row("M"));
  });

  it("falls back to the previous index, clamped to the last row, when the hash disappears (TC-650)", () => {
    // Case: TC-650 (K04, K05 / A8.1-7)
    focusRow("M");
    loadCommits([node("N", ["R"]), node("R", [])]);
    expect(rowsWithTabStop()).toEqual(["R"]);

    loadCommits(standardCommits());
    focusRow("R");
    loadCommits([node("N", [])]);
    expect(rowsWithTabStop()).toEqual(["N"]);
  });

  it("marks every other row programmatic-only and uses no positive tabindex (TC-651)", () => {
    // Case: TC-651
    expect(row("M").getAttribute("tabindex")).toBe(TAB_STOP);
    expect(row("N").getAttribute("tabindex")).toBe(PROGRAMMATIC_ONLY);
    expect(row("R").getAttribute("tabindex")).toBe(PROGRAMMATIC_ONLY);
    const positive = Array.from(document.querySelectorAll<HTMLElement>("[tabindex]")).filter(
      (elem) => elem.tabIndex > 0
    );
    expect(positive).toEqual([]);
  });

  it("syncs the target to a clicked or Ctrl-clicked row (TC-652)", () => {
    // Case: TC-652
    focusRow("N");
    fire(row("R"), "click");
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(posts("commitDetails")).toHaveLength(1);
    respondDetails("R");
    clearPosts();

    fire(row("N"), "click", { ctrlKey: true });
    expect(rowsWithTabStop()).toEqual(["N"]);
    expect(posts("compareCommits")).toHaveLength(1);
  });

  it("keeps the target while focus is outside the list and re-enters at it (TC-653)", () => {
    // Case: TC-653
    focusRow("M");
    document.getElementById("refreshBtn")!.focus();
    expect(rowsWithTabStop()).toEqual(["M"]);
    focusRow("M");
    expect(document.activeElement).toBe(row("M"));
  });

  it("keeps the target through a loading view but not through accepted zero rows (TC-654)", () => {
    // Case: TC-654
    focusRow("N");
    press(row("N"), "r", { ctrlKey: true });
    expect(document.getElementById("loadingHeader")).not.toBeNull();
    respondToRefresh(standardCommits());
    expect(rowsWithTabStop()).toEqual(["N"]);

    // Accepted zero rows reset the target (the focus parked in the list would otherwise be
    // resolved again by its keys), so the next response applies the HEAD rule.
    document.getElementById("refreshBtn")!.focus();
    loadCommits([], { head: null });
    expect(table().getAttribute("tabindex")).toBe(TAB_STOP);
    loadCommits(standardCommits());
    expect(rowsWithTabStop()).toEqual(["M"]);
  });

  it("disables the current button while HEAD is absent or unloaded (TC-655)", () => {
    // Case: TC-655 (K47 / A8.3-1)
    const currentBtn = document.getElementById("currentBtn")!;
    loadCommits(standardCommits(), { head: null });
    expect(currentBtn.hasAttribute("disabled")).toBe(true);
    focusRow("N");
    press(row("N"), "h", { ctrlKey: true });
    expect(document.querySelectorAll(".flash")).toHaveLength(0);

    loadCommits(standardCommits(), { head: "Z" });
    expect(currentBtn.hasAttribute("disabled")).toBe(true);

    loadCommits(standardCommits(), { head: "M" });
    expect(currentBtn.hasAttribute("disabled")).toBe(false);
  });

  it("treats a single row, the working tree row and stash rows as ordinary targets (TC-656)", () => {
    // Case: TC-656 (A8.3-1)
    loadCommits([node("only", [])], { head: "only" });
    expect(rowsWithTabStop()).toEqual(["only"]);
    const only = focusRow("only");
    expect(press(only, "ArrowDown").defaultPrevented).toBe(false);
    expect(press(only, "ArrowUp").defaultPrevented).toBe(false);
    expect(posts()).toEqual([]);

    loadCommits(uncommittedCommits());
    const uncommitted = focusRow(UNCOMMITTED_CHANGES_HASH);
    expect(uncommitted.getAttribute("tabindex")).toBe(TAB_STOP);
    expect(press(uncommitted, "ArrowDown").defaultPrevented).toBe(true);
    expect(document.activeElement).toBe(row("N"));
    expect(rowsWithTabStop()).toEqual(["N"]);

    loadCommits(stashCommits());
    const stash = focusRow(STASH_HASH);
    press(stash, "ArrowDown");
    expect(document.activeElement).toBe(row("M"));
    press(row("M"), "ArrowUp");
    expect(document.activeElement).toBe(row(STASH_HASH));
    expect(posts()).toEqual([]);
  });

  it("never takes focus back from the find input or from body on a re-accepted response (TC-657)", () => {
    // Case: TC-657 (A8.2-4)
    const focusSpy = vi.spyOn(HTMLElement.prototype, "focus");
    focusRow("M");
    press(row("M"), "f", { ctrlKey: true });
    const findInput = document.getElementById("findInput")!;
    expect(document.activeElement).toBe(findInput);
    focusSpy.mockClear();
    loadCommits(standardCommits());
    expect(document.activeElement).toBe(findInput);
    expect(focusSpy.mock.instances.filter((elem) => elem instanceof HTMLTableRowElement)).toEqual(
      []
    );

    findInput.blur();
    fire(document.getElementById("findClose")!, "click");
    expect(document.activeElement).toBe(document.body);
    focusSpy.mockClear();
    loadCommits(standardCommits());
    expect(document.activeElement).toBe(document.body);
    expect(focusSpy).not.toHaveBeenCalled();
  });
});

/* ------------------------------------------------------------------ */
/* S70: row keys per state                                            */
/* ------------------------------------------------------------------ */

// @see docs/testing/perspectives/web/main-test/13-keyboard-accessibility-01.md
describe("row keys per state (S70)", () => {
  it("moves only the target on ArrowDown without details (TC-658)", () => {
    // Case: TC-658 (K07 / A8.1-1 main regression: pre-implementation nothing moved)
    focusRow("M");
    const event = press(row("M"), "ArrowDown");

    expect(document.activeElement).toBe(row("R"));
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(posts("commitDetails")).toEqual([]);
    expect(event.defaultPrevented).toBe(true);
    expect(details()).toBeNull();
  });

  it("opens the single details once on Enter, ignoring repeat and keyup (TC-659)", () => {
    // Case: TC-659 (K08 / A8.1-1 / A8.3-2)
    focusRow("M");
    press(row("M"), "ArrowDown");
    const target = row("R");
    target.dispatchEvent(
      new KeyboardEvent("keydown", { key: "Enter", bubbles: true, cancelable: true })
    );
    expect(posts("commitDetails")).toEqual([expect.objectContaining({ commitHash: "R" })]);
    target.dispatchEvent(
      new KeyboardEvent("keydown", { key: "Enter", bubbles: true, cancelable: true, repeat: true })
    );
    target.dispatchEvent(
      new KeyboardEvent("keyup", { key: "Enter", bubbles: true, cancelable: true })
    );

    expect(posts("commitDetails")).toHaveLength(1);
    expect(detailsOpenRows()).toEqual(["R"]);
  });

  it("does not re-request or close the same single details on Enter (TC-660)", () => {
    // Case: TC-660 (K09)
    openDetails("R");
    clearPosts();
    const detailsElem = details();
    focusRow("R");
    press(row("R"), "Enter");

    expect(posts("commitDetails")).toEqual([]);
    expect(details()).toBe(detailsElem);
    expect(detailsOwner()).toBe("R");
  });

  it("keeps the open details when the target moves onto the row that owns them (TC-661)", () => {
    // Case: TC-661 (K10)
    openDetails("M");
    clearPosts();
    focusRow("N");
    press(row("N"), "ArrowDown");

    expect(rowsWithTabStop()).toEqual(["M"]);
    expect(document.activeElement).toBe(row("M"));
    expect(detailsOwner()).toBe("M");
    expect(posts("commitDetails")).toEqual([]);
  });

  it("moves the single details with the target (TC-662)", () => {
    // Case: TC-662 (K11 / A8.1-2)
    openDetails("M");
    clearPosts();
    scrollContainer().scrollTop = 0;
    focusRow("M");
    press(row("M"), "ArrowDown");

    expect(document.activeElement).toBe(row("R"));
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(posts("commitDetails")).toEqual([expect.objectContaining({ commitHash: "R" })]);
    expect(detailsOwner()).toBe("R");
  });

  it("moves only the target while comparing (TC-663)", () => {
    // Case: TC-663 (K12 / A8.1-2)
    startCompare("N", "M");
    clearPosts();
    focusRow("M");
    press(row("M"), "ArrowDown");

    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(document.activeElement).toBe(row("R"));
    expect(detailsOpenRows()).toEqual(["N"]);
    expect(compareTargetRows()).toEqual(["M"]);
    expect(posts()).toEqual([]);
  });

  it("ignores modified arrows while comparing (TC-664)", () => {
    // Case: TC-664 (K13)
    const graphSpies = [
      vi.spyOn(Graph.prototype, "getFirstParentIndex"),
      vi.spyOn(Graph.prototype, "getFirstChildIndex"),
      vi.spyOn(Graph.prototype, "getAlternativeParentIndex"),
      vi.spyOn(Graph.prototype, "getAlternativeChildIndex")
    ];
    startCompare("N", "M");
    clearPosts();
    focusRow("R");

    const events = [
      press(row("R"), "ArrowDown", { ctrlKey: true }),
      press(row("R"), "ArrowDown", { metaKey: true }),
      press(row("R"), "ArrowUp", { ctrlKey: true, shiftKey: true })
    ];

    expect(document.activeElement).toBe(row("R"));
    for (const spy of graphSpies) expect(spy).not.toHaveBeenCalled();
    expect(posts()).toEqual([]);
    expect(events.map((event) => event.defaultPrevented)).toEqual([false, false, false]);
  });

  it("ends the comparison and opens the single details on Enter (TC-665)", () => {
    // Case: TC-665 (K14)
    startCompare("N", "M");
    clearPosts();
    focusRow("R");
    press(row("R"), "Enter");

    expect(compareTargetRows()).toEqual([]);
    expect(details()!.textContent).not.toContain("Displaying all changes");
    expect(posts("commitDetails")).toEqual([expect.objectContaining({ commitHash: "R" })]);
    expect(detailsOpenRows()).toEqual(["R"]);
  });

  it("opens details on a modified Enter when none are open, like a modified click (TC-666)", () => {
    // Case: TC-666 (K15)
    focusRow("M");
    press(row("M"), "Enter", { ctrlKey: true });
    const keyboardPosts = posts();
    expect(keyboardPosts).toEqual([
      expect.objectContaining({ command: "commitDetails", commitHash: "M" })
    ]);
    expect(posts("compareCommits")).toEqual([]);

    fire(document.getElementById("commitDetailsClose")!, "click");
    clearPosts();
    fire(row("M"), "click", { ctrlKey: true });
    expect(posts()).toEqual(keyboardPosts);
  });

  it("makes another row the compare target on a modified Enter (TC-667)", () => {
    // Case: TC-667 (K15 / A8.1-2)
    openDetails("N");
    clearPosts();
    focusRow("M");
    press(row("M"), "Enter", { ctrlKey: true });
    const keyboardPosts = posts();
    expect(compareTargetRows()).toEqual(["M"]);
    expect(keyboardPosts).toEqual([
      expect.objectContaining({ command: "compareCommits", fromHash: "M", toHash: "N" })
    ]);

    closeEverything();
    openDetails("N");
    clearPosts();
    fire(row("M"), "click", { ctrlKey: true });
    expect(posts()).toEqual(keyboardPosts);
  });

  it("cancels the comparison on a modified Enter at the compare target (TC-668)", () => {
    // Case: TC-668 (K15)
    startCompare("N", "M");
    clearPosts();
    focusRow("M");
    press(row("M"), "Enter", { ctrlKey: true });

    expect(compareTargetRows()).toEqual([]);
    expect(detailsOwner()).toBe("N");
    expect(details()!.textContent).not.toContain("Displaying all changes");
    expect(posts()).toEqual([]);
  });

  it("keeps the state on a modified Enter at the details origin row (TC-669)", () => {
    // Case: TC-669 (K15)
    openDetails("N");
    clearPosts();
    focusRow("N");
    press(row("N"), "Enter", { ctrlKey: true });

    expect(detailsOwner()).toBe("N");
    expect(compareTargetRows()).toEqual([]);
    expect(posts()).toEqual([]);
  });

  it("walks the first parent and child from the target, not from the details (TC-670)", () => {
    // Case: TC-670 (K16 / A8.2-1)
    const parentSpy = vi.spyOn(Graph.prototype, "getFirstParentIndex");
    const childSpy = vi.spyOn(Graph.prototype, "getFirstChildIndex");
    openDetails("N");
    clearPosts();
    focusRow("M");

    press(row("M"), "ArrowDown", { ctrlKey: true });
    expect(parentSpy).toHaveBeenCalledTimes(1);
    expect(parentSpy).toHaveBeenCalledWith(1);
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(posts("commitDetails")).toEqual([expect.objectContaining({ commitHash: "R" })]);
    respondDetails("R");
    clearPosts();

    focusRow("M");
    press(row("M"), "ArrowUp", { metaKey: true });
    expect(childSpy).toHaveBeenCalledTimes(1);
    expect(childSpy).toHaveBeenCalledWith(1);
    expect(rowsWithTabStop()).toEqual(["N"]);
    expect(posts("commitDetails")).toEqual([expect.objectContaining({ commitHash: "N" })]);
  });

  it("walks the alternative parent and child with Shift (TC-671)", () => {
    // Case: TC-671 (K16 / A8.2-1; S31 TC-172..TC-174 carried over)
    const altParentSpy = vi.spyOn(Graph.prototype, "getAlternativeParentIndex");
    const altChildSpy = vi.spyOn(Graph.prototype, "getAlternativeChildIndex");
    loadCommits(mergeCommits());
    focusRow("M");

    press(row("M"), "ArrowDown", { ctrlKey: true, shiftKey: true });
    expect(altParentSpy).toHaveBeenCalledWith(1);
    expect(document.activeElement).toBe(row("B"));
    expect(rowsWithTabStop()).toEqual(["B"]);

    focusRow("R");
    press(row("R"), "ArrowUp", { metaKey: true, shiftKey: true });
    expect(altChildSpy).toHaveBeenCalledWith(4);
    const destination = altChildSpy.mock.results[0].value as number;
    expect(destination).toBeGreaterThanOrEqual(0);
    expect(document.activeElement!.getAttribute("data-id")).toBe(destination.toString());
    expect(posts()).toEqual([]);
  });

  it("leaves unloaded parents and the first child unconsumed without a request (TC-672)", () => {
    // Case: TC-672 (K16 / A8.3-1; S30 TC-170 / TC-171 carried over)
    const parentSpy = vi.spyOn(Graph.prototype, "getFirstParentIndex");
    const childSpy = vi.spyOn(Graph.prototype, "getFirstChildIndex");
    focusRow("R");
    const down = press(row("R"), "ArrowDown", { ctrlKey: true });
    expect(parentSpy).toHaveReturnedWith(-1);
    expect(document.activeElement).toBe(row("R"));
    expect(down.defaultPrevented).toBe(false);

    focusRow("N");
    const up = press(row("N"), "ArrowUp", { ctrlKey: true });
    expect(childSpy).toHaveReturnedWith(-1);
    expect(document.activeElement).toBe(row("N"));
    expect(up.defaultPrevented).toBe(false);
    expect(posts()).toEqual([]);
  });

  it("does not consume the table ends with or without details (TC-673)", () => {
    // Case: TC-673 (S29 TC-166 / TC-167 carried over)
    const results: boolean[] = [];
    for (const withDetails of [false, true]) {
      if (withDetails) openDetails("M");
      clearPosts();
      scrollContainer().scrollTop = 0;
      focusRow("N");
      results.push(press(row("N"), "ArrowUp").defaultPrevented);
      expect(document.activeElement).toBe(row("N"));
      focusRow("R");
      results.push(press(row("R"), "ArrowDown").defaultPrevented);
      expect(document.activeElement).toBe(row("R"));
      expect(posts()).toEqual([]);
      expect(scrollContainer().scrollTop).toBe(0);
    }
    expect(results).toEqual([false, false, false, false]);
  });

  it("leaves Shift and Alt Enter unassigned (TC-674)", () => {
    // Case: TC-674
    focusRow("M");
    const events = [
      press(row("M"), "Enter", { shiftKey: true }),
      press(row("M"), "Enter", { altKey: true }),
      press(row("M"), "Enter", { ctrlKey: true, altKey: true })
    ];
    expect(posts()).toEqual([]);
    expect(details()).toBeNull();
    expect(events.map((event) => event.defaultPrevented)).toEqual([false, false, false]);
  });

  it("resolves a label descendant to its row and ignores contenteditable descendants (TC-675)", () => {
    // Case: TC-675 (A8.3-3)
    const [label] = labelsOf("M");
    expect(label.getAttribute("tabindex")).toBe(TAB_STOP);
    label.focus();
    const nameSpan = label.querySelector<HTMLElement>(".gitRefName")!;
    press(nameSpan, "ArrowDown");
    expect(document.activeElement).toBe(row("R"));
    expect(posts("commitDetails")).toEqual([]);

    const editable = document.createElement("div");
    editable.setAttribute("contenteditable", "true");
    editable.className = "keyboardTestExtra";
    const child = editable.appendChild(document.createElement("span"));
    row("M").lastElementChild!.appendChild(editable);
    focusRow("M");
    const event = press(child, "ArrowDown");
    expect(document.activeElement).toBe(row("M"));
    expect(event.defaultPrevented).toBe(false);
    expect(posts()).toEqual([]);
  });
});

/* ------------------------------------------------------------------ */
/* S71: file history and path highlight                               */
/* ------------------------------------------------------------------ */

// @see docs/testing/perspectives/web/main-test/13-keyboard-accessibility-01.md
describe("arrows while the file history or a path highlight is active (S71)", () => {
  it("moves to the next match, makes it the target and opens its details (TC-676)", () => {
    // Case: TC-676 (K17 / A8.2-1)
    const navigateSpy = vi.spyOn(FileHistoryController.prototype, "navigate");
    requestFileHistory(["M", "R"]);
    clearPosts();
    focusRow("M");
    const event = press(row("M"), "ArrowDown");

    expect(navigateSpy).toHaveBeenCalledTimes(1);
    expect(navigateSpy).toHaveBeenCalledWith(1, true);
    expect(navigateSpy).toHaveReturnedWith("R");
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(document.activeElement).toBe(row("R"));
    expect(posts("commitDetails")).toEqual([expect.objectContaining({ commitHash: "R" })]);
    expect(event.defaultPrevented).toBe(true);
  });

  it("consumes plain arrows while the history request is pending (TC-677)", () => {
    // Case: TC-677 (K18)
    const navigateSpy = vi.spyOn(FileHistoryController.prototype, "navigate");
    requestFileHistory(null);
    clearPosts();
    scrollContainer().scrollTop = 0;
    focusRow("M");
    const event = press(row("M"), "ArrowDown");

    expect(navigateSpy).not.toHaveBeenCalled();
    expect(posts()).toEqual([]);
    expect(document.activeElement).toBe(row("M"));
    expect(scrollContainer().scrollTop).toBe(0);
    expect(event.defaultPrevented).toBe(true);
  });

  it("consumes the history edge without a request (TC-678)", () => {
    // Case: TC-678 (K18 / A8.2-1)
    const navigateSpy = vi.spyOn(FileHistoryController.prototype, "navigate");
    requestFileHistory(["M", "R"]);
    focusRow("M");
    press(row("M"), "ArrowDown");
    respondDetails("R");
    clearPosts();
    navigateSpy.mockClear();
    const event = press(row("R"), "ArrowDown");

    expect(navigateSpy).toHaveBeenCalledTimes(1);
    expect(navigateSpy).toHaveReturnedWith(null);
    expect(posts()).toEqual([]);
    expect(document.activeElement).toBe(row("R"));
    expect(event.defaultPrevented).toBe(true);
  });

  it("consumes Ctrl / Cmd arrows during the history without moving (TC-679)", () => {
    // Case: TC-679 (K18)
    const navigateSpy = vi.spyOn(FileHistoryController.prototype, "navigate");
    const parentSpy = vi.spyOn(Graph.prototype, "getFirstParentIndex");
    const altChildSpy = vi.spyOn(Graph.prototype, "getAlternativeChildIndex");
    requestFileHistory(["M", "R"]);
    clearPosts();
    focusRow("M");
    const events = [
      press(row("M"), "ArrowDown", { ctrlKey: true }),
      press(row("M"), "ArrowUp", { metaKey: true, shiftKey: true })
    ];

    expect(navigateSpy).not.toHaveBeenCalled();
    expect(parentSpy).not.toHaveBeenCalled();
    expect(altChildSpy).not.toHaveBeenCalled();
    expect(posts()).toEqual([]);
    expect(events.map((event) => event.defaultPrevented)).toEqual([true, true]);
  });

  it("lets the comparison win over the history (TC-680)", () => {
    // Case: TC-680 (S64 TC-589 contract change)
    const navigateSpy = vi.spyOn(FileHistoryController.prototype, "navigate");
    requestFileHistory(["M", "R"]);
    expect(details()).toBeNull();
    startCompare("N", "M");
    clearPosts();
    focusRow("M");
    press(row("M"), "ArrowDown");

    expect(navigateSpy).not.toHaveBeenCalled();
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(compareTargetRows()).toEqual(["M"]);
    expect(posts()).toEqual([]);
  });

  it("does not capture Shift-only or Alt arrows in the history branch (TC-681)", () => {
    // Case: TC-681 (K18)
    const navigateSpy = vi.spyOn(FileHistoryController.prototype, "navigate");
    requestFileHistory(["M", "R"]);
    clearPosts();
    focusRow("M");
    const events = [
      press(row("M"), "ArrowDown", { shiftKey: true }),
      press(row("M"), "ArrowUp", { altKey: true }),
      press(row("M"), "ArrowDown", { ctrlKey: true, altKey: true })
    ];

    expect(navigateSpy).not.toHaveBeenCalled();
    expect(posts()).toEqual([]);
    expect(document.activeElement).toBe(row("M"));
    expect(events.map((event) => event.defaultPrevented)).toEqual([false, false, false]);
  });

  it("neither follows the move nor clears on Escape while a path is highlighted (TC-683)", () => {
    // Case: TC-683 (K43 / A8.2-2)
    const highlightSpy = vi.spyOn(Graph.prototype, "setPathHighlight");
    highlightThroughMenu("M");
    const callsAfterSelect = highlightSpy.mock.calls.length;
    focusRow("M");
    press(row("M"), "ArrowDown");

    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(document.getElementById("pathHighlightHash")!.getAttribute("title")).toBe("M");
    expect(highlightSpy).toHaveBeenCalledTimes(callsAfterSelect);

    pressEscape(row("R"));
    expect(pathBar().classList.contains(CLASS_ACTIVE)).toBe(true);
    expect(highlightSpy).toHaveBeenCalledTimes(callsAfterSelect);
  });
});

/* ------------------------------------------------------------------ */
/* S72: configurable shortcuts and the global Escape on keydown       */
/* ------------------------------------------------------------------ */

// @see docs/testing/perspectives/web/main-test/13-keyboard-accessibility-01.md
describe("configurable shortcuts and the global Escape chain (S72)", () => {
  it("does not process list keys from the toolbar (TC-684)", () => {
    // Case: TC-684 (K19 / A8.2-4)
    for (const id of ["refreshBtn", "branchCleanupBtn"]) {
      const button = document.getElementById(id)!;
      button.focus();
      press(button, "ArrowDown");
      press(button, "Enter");
      press(button, "h", { ctrlKey: true });
      expect(rowsWithTabStop()).toEqual(["M"]);
      expect(document.activeElement).toBe(button);
    }
    const trigger = dropdownTrigger("branchSelect");
    trigger.focus();
    press(trigger, "ArrowDown");
    expect(rowsWithTabStop()).toEqual(["M"]);
    expect(posts("commitDetails")).toEqual([]);
    expect(document.querySelectorAll(".flash")).toHaveLength(0);
  });

  it("leaves inputs and contenteditable elements to their own keys (TC-685)", () => {
    // Case: TC-685 (K19 / A8.3-3; S46 TC-262 / S64 TC-591 contract change)
    const showSpy = vi.spyOn(FindWidget.prototype, "show");
    focusRow("M");
    press(row("M"), "f", { ctrlKey: true });
    expect(showSpy).toHaveBeenCalledTimes(1);
    const findInput = document.getElementById("findInput")!;
    expect(document.activeElement).toBe(findInput);
    showSpy.mockClear();
    clearPosts();

    const fromInput = [
      press(findInput, "ArrowDown"),
      press(findInput, "Enter"),
      press(findInput, "f", { ctrlKey: true })
    ];
    expect(showSpy).not.toHaveBeenCalled();
    expect(fromInput.map((event) => event.defaultPrevented)).toEqual([false, false, false]);

    const textarea = document.body.appendChild(document.createElement("textarea"));
    textarea.className = "keyboardTestExtra";
    const editable = document.body.appendChild(document.createElement("div"));
    editable.className = "keyboardTestExtra";
    editable.setAttribute("contenteditable", "true");
    const child = editable.appendChild(document.createElement("span"));
    for (const target of [textarea, editable, child]) {
      expect(press(target, "ArrowDown").defaultPrevented).toBe(false);
      expect(press(target, "Enter").defaultPrevented).toBe(false);
      press(target, "f", { ctrlKey: true });
    }
    expect(showSpy).not.toHaveBeenCalled();
    expect(rowsWithTabStop()).toEqual(["M"]);
    expect(posts()).toEqual([]);
  });

  it("does not process list keys from the path highlight mode select (TC-687)", () => {
    // Case: TC-687 (K19 / K43 / A8.2-4)
    const highlightSpy = vi.spyOn(Graph.prototype, "setPathHighlight");
    highlightThroughMenu("M");
    const callsAfterSelect = highlightSpy.mock.calls.length;
    clearPosts();
    const select = document.getElementById("pathHighlightMode")!;
    select.focus();
    const events = [press(select, "ArrowDown"), press(select, "Enter")];

    expect(rowsWithTabStop()).toEqual(["M"]);
    expect(events.map((event) => event.defaultPrevented)).toEqual([false, false]);
    expect(posts()).toEqual([]);
    expect(highlightSpy).toHaveBeenCalledTimes(callsAfterSelect);
  });

  it("applies the configurable shortcuts from a row and from a ref label (TC-688)", () => {
    // Case: TC-688 (S10 TC-065..TC-074 carried over with the row / label precondition)
    const showSpy = vi.spyOn(FindWidget.prototype, "show");
    const origins: (() => HTMLElement)[] = [() => focusRow("M"), () => labelsOf("M")[0]];
    for (const origin of origins) {
      let elem = origin();
      elem.focus();
      press(elem, "F", { ctrlKey: true, shiftKey: true });
      expect(showSpy).toHaveBeenLastCalledWith(true);
      fire(document.getElementById("findClose")!, "click");

      elem = origin();
      elem.focus();
      press(elem, "h", { metaKey: true });
      expect(row("M").classList.contains("flash")).toBe(true);
      row("M").classList.remove("flash");

      elem = origin();
      elem.focus();
      const unmapped = press(elem, "x", { ctrlKey: true });
      expect(unmapped.defaultPrevented).toBe(false);
      const composing = press(elem, "f", { ctrlKey: true, isComposing: true });
      expect(composing.defaultPrevented).toBe(false);
      expect(showSpy).toHaveBeenCalledTimes(1);

      press(elem, "r", { ctrlKey: true });
      expect(document.getElementById("loadingHeader")).not.toBeNull();
      respondToRefresh(standardCommits());
      showSpy.mockClear();
    }
    expect(posts("commitDetails")).toEqual([]);
  });

  it("closes exactly one layer per Escape keydown in the existing order (TC-689)", async () => {
    // Case: TC-689 (S12 / S58 / S65 carried over to keydown)
    const dialogs = await import("../../web/dialogs");
    const exitSpy = vi.spyOn(FileHistoryController.prototype, "exit");
    const cancelSpy = vi.spyOn(Dropdown.prototype, "cancelAndClose");

    // Menu under a dialog: the menu goes first, then the dialog
    fire(row("M"), "contextmenu");
    dialogs.showConfirmationDialog("Confirm?", () => {}, null);
    expect(menuIsActive()).toBe(true);
    expect(dialogIsActive()).toBe(true);
    pressEscape();
    expect(menuIsActive()).toBe(false);
    expect(dialogIsActive()).toBe(true);
    pressEscape();
    expect(dialogIsActive()).toBe(false);

    // Each dropdown cancels (the real components close one another on open)
    for (const id of ["repoSelect", "branchSelect", "authorSelect"]) {
      openDropdown(id);
      pressEscape();
      expect(dropdownIsOpen(id)).toBe(false);
    }
    expect(cancelSpy).toHaveBeenCalledTimes(3);
    expect(cancelSpy).toHaveBeenCalledWith("keyboard");
    expect(posts("loadCommits")).toEqual([]);

    // Find widget before the details
    openDetails("M");
    focusRow("M");
    press(row("M"), "f", { ctrlKey: true });
    expect(findWidgetIsVisible()).toBe(true);
    pressEscape();
    expect(findWidgetIsVisible()).toBe(false);
    expect(details()).not.toBeNull();
    pressEscape();
    expect(details()).toBeNull();

    // Details before the history
    requestFileHistory(["M", "R"]);
    openDetails("R");
    pressEscape();
    expect(details()).toBeNull();
    expect(historyIsActive()).toBe(true);
    expect(exitSpy).not.toHaveBeenCalled();
    pressEscape();
    expect(exitSpy).toHaveBeenCalledTimes(1);
    expect(exitSpy).toHaveBeenCalledWith(true);
    expect(historyIsActive()).toBe(false);
  });

  it("cancels the multi-select on Escape keydown and keeps the details on keyup (TC-690)", () => {
    // Case: TC-690 (K24 / A8.1-3 / A8.3-2 main regression: pre-implementation keyup closed details)
    openDetails("M");
    clearPosts();
    openDropdown("branchSelect");
    const filter = document.querySelector<HTMLInputElement>("#branchSelect .dropdownFilterInput")!;
    expect(document.activeElement).toBe(filter);
    const selectedValues = (): (string | null)[] =>
      Array.from(
        document.querySelectorAll<HTMLElement>(
          '#branchSelect .dropdownOption[aria-selected="true"]'
        )
      ).map((option) => option.textContent);
    const selectedBefore = selectedValues();
    press(filter, "ArrowDown");
    press(document.activeElement!, "ArrowDown");
    const option = document.activeElement as HTMLElement;
    expect(option.classList.contains("dropdownOption")).toBe(true);
    press(option, " ");
    expect(selectedValues()).not.toEqual(selectedBefore);

    const keydown = pressEscape(document.activeElement!);
    expect(keydown.defaultPrevented).toBe(true);
    expect(dropdownIsOpen("branchSelect")).toBe(false);
    expect(selectedValues()).toEqual(selectedBefore);
    expect(posts("loadCommits")).toEqual([]);
    expect(document.activeElement).toBe(dropdownTrigger("branchSelect"));

    releaseEscape(document.activeElement!);
    expect(details()).not.toBeNull();
    expect(detailsOwner()).toBe("M");
    expect(findWidgetIsVisible()).toBe(false);
  });

  it("does not close further layers on Escape repeat or keyup (TC-691)", () => {
    // Case: TC-691
    openDetails("M");
    focusRow("M");
    press(row("M"), "f", { ctrlKey: true });
    expect(findWidgetIsVisible()).toBe(true);

    pressEscape();
    expect(findWidgetIsVisible()).toBe(false);
    expect(details()).not.toBeNull();
    pressEscape(document, { repeat: true });
    pressEscape(document, { repeat: true });
    expect(details()).not.toBeNull();
    releaseEscape();
    expect(details()).not.toBeNull();
  });

  it("cancels every dropdown on Escape instead of applying it (TC-692)", () => {
    // Case: TC-692 (K24; S12 TC-085..TC-087 / S65 TC-596 contract change)
    const closeSpy = vi.spyOn(Dropdown.prototype, "close");
    const cancelSpy = vi.spyOn(Dropdown.prototype, "cancelAndClose");
    for (const id of ["repoSelect", "branchSelect", "authorSelect"]) {
      openDropdown(id);
      const filter = document.querySelector<HTMLInputElement>(`#${id} .dropdownFilterInput`)!;
      press(filter, "ArrowDown");
      clearPosts();
      closeSpy.mockClear();
      cancelSpy.mockClear();

      pressEscape();

      expect(dropdownIsOpen(id)).toBe(false);
      expect(cancelSpy).toHaveBeenCalledTimes(1);
      expect(closeSpy).not.toHaveBeenCalled();
      expect(posts("loadCommits")).toEqual([]);
      expect(document.activeElement).toBe(dropdownTrigger(id));
    }
  });

  it("ignores an Escape a local UI already consumed (TC-693)", () => {
    // Case: TC-693 (A8.3-3)
    openDetails("M");
    const consume = (event: Event) => event.preventDefault();
    document.addEventListener("keydown", consume, { capture: true, once: true });
    pressEscape();

    expect(details()).not.toBeNull();
    expect(detailsOwner()).toBe("M");
  });

  it("keeps the cleanup panel and the path highlight out of the Escape chain (TC-695)", () => {
    // Case: TC-695 (A8.2-2)
    const highlightSpy = vi.spyOn(Graph.prototype, "setPathHighlight");
    fire(document.getElementById("branchCleanupBtn")!, "click");
    const panel = document.getElementById("branchCleanupPanel")!;
    expect(panel.hasAttribute("hidden")).toBe(false);
    highlightThroughMenu("M");
    const callsAfterSelect = highlightSpy.mock.calls.length;

    pressEscape();

    expect(panel.hasAttribute("hidden")).toBe(false);
    expect(pathBar().classList.contains(CLASS_ACTIVE)).toBe(true);
    expect(highlightSpy).toHaveBeenCalledTimes(callsAfterSelect);
  });

  it("ignores Escape that belongs to an IME composition (TC-696)", () => {
    // Case: TC-696 (A8.3-2; the guard itself is web/keyboardNavigation-test.md S2)
    openDetails("M");
    focusRow("M");
    row("M").dispatchEvent(new CompositionEvent("compositionstart", { bubbles: true }));
    pressEscape(row("M"), { isComposing: true });
    row("M").dispatchEvent(new CompositionEvent("compositionend", { bubbles: true }));
    releaseEscape(row("M"));

    expect(details()).not.toBeNull();
    expect(detailsOwner()).toBe("M");
  });

  it("has no side effects when nothing is open (TC-699)", () => {
    // Case: TC-699 (S12 TC-090 / S58 TC-463 / S65 TC-599 carried over)
    const exitSpy = vi.spyOn(FileHistoryController.prototype, "exit");
    const cancelSpy = vi.spyOn(Dropdown.prototype, "cancelAndClose");
    focusRow("M");
    pressEscape(row("M"));
    releaseEscape(row("M"));

    expect(exitSpy).not.toHaveBeenCalled();
    expect(cancelSpy).not.toHaveBeenCalled();
    expect(document.querySelectorAll(".refOverflowPopup")).toHaveLength(0);
    expect(document.activeElement).toBe(row("M"));
    expect(rowsWithTabStop()).toEqual(["M"]);
  });
});

/* ------------------------------------------------------------------ */
/* S73: Tab order inside the list                                     */
/* ------------------------------------------------------------------ */

// @see docs/testing/perspectives/web/main-test/13-keyboard-accessibility-02.md
describe("Tab boundary between the target row's labels and the details (S73)", () => {
  function detailsStops(): HTMLElement[] {
    return Array.from(details()!.querySelectorAll<HTMLElement>("a[href]"));
  }

  beforeEach(() => {
    loadCommits(labelsOnLastRowCommits(), { head: "R" });
    openDetails("N");
    clearPosts();
  });

  it("goes from the last label of the target row into the details of another row (TC-702)", () => {
    // Case: TC-702 (K20)
    const [first, second] = labelsOf("R");
    const [firstDetailsStop] = detailsStops();
    expect(firstDetailsStop).toBeDefined();
    const target = focusRow("R");

    expect(press(target, "Tab").defaultPrevented).toBe(false);
    first.focus();
    expect(press(first, "Tab").defaultPrevented).toBe(false);
    second.focus();
    const boundary = press(second, "Tab");

    expect(boundary.defaultPrevented).toBe(true);
    expect(document.activeElement).toBe(firstDetailsStop);
  });

  it("returns from the first details control to the last label with Shift+Tab (TC-703)", () => {
    // Case: TC-703 (K20)
    focusRow("R");
    const [, second] = labelsOf("R");
    const [firstDetailsStop] = detailsStops();
    firstDetailsStop.focus();

    const boundary = press(firstDetailsStop, "Tab", { shiftKey: true });

    expect(boundary.defaultPrevented).toBe(true);
    expect(document.activeElement).toBe(second);
    expect(press(second, "Tab", { shiftKey: true }).defaultPrevented).toBe(false);
  });

  it("keeps labels of other rows out of the tab order (TC-704)", () => {
    // Case: TC-704
    loadCommits(standardCommits(), { head: "R" });
    for (const label of labelsOf("M"))
      expect(label.getAttribute("tabindex")).toBe(PROGRAMMATIC_ONLY);
    focusRow("R");
    press(row("R"), "ArrowUp");
    for (const label of labelsOf("M")) expect(label.getAttribute("tabindex")).toBe(TAB_STOP);
  });

  it("does not consume Tab at the end of the details or Shift+Tab on the row (TC-707)", () => {
    // Case: TC-707
    const stops = detailsStops();
    const last = stops[stops.length - 1];
    last.focus();
    expect(press(last, "Tab").defaultPrevented).toBe(false);
    expect(document.activeElement).toBe(last);

    const target = focusRow("R");
    expect(press(target, "Tab", { shiftKey: true }).defaultPrevented).toBe(false);
    expect(document.activeElement).toBe(target);
  });
});

/* ------------------------------------------------------------------ */
/* S74: focus restore after re-render and menu context                */
/* ------------------------------------------------------------------ */

// @see docs/testing/perspectives/web/main-test/13-keyboard-accessibility-02.md
describe("focus restore after re-render and the kept menu context (S74)", () => {
  it("does not take focus back after the user left the loading view (TC-709)", () => {
    // Case: TC-709 (K21 / A8.3-5)
    focusRow("M");
    press(row("M"), "r", { ctrlKey: true });
    const refreshBtn = document.getElementById("refreshBtn")!;
    refreshBtn.focus();
    clearPosts();

    respondToRefresh(standardCommits());

    expect(document.activeElement).toBe(refreshBtn);
    expect(rowsWithTabStop()).toEqual(["M"]);
    expect(posts()).toEqual([]);
  });

  it("restores the focused row of the same repository after a forced re-render (TC-710)", () => {
    // Case: TC-710 (K22 / A8.1-7); the ref-label variant needs the Task 7 keys
    const oldRow = focusRow("M");
    scrollContainer().scrollTop = 0;
    loadCommits(standardCommits(), { hard: true });

    expect(oldRow.isConnected).toBe(false);
    expect(document.activeElement).toBe(row("M"));
    expect(scrollContainer().scrollTop).toBe(0);
    expect(posts()).toEqual([]);
  });

  it("restores the focused ref label of the same repository after a forced re-render (TC-710)", () => {
    // Case: TC-710 (K22 / A8.1-7), ref-label variant: the label key resolves to the new button
    const [oldLabel] = labelsOf("M");
    oldLabel.focus();
    expect(document.activeElement).toBe(oldLabel);
    loadCommits(standardCommits(), { hard: true });

    const [newLabel] = labelsOf("M");
    expect(oldLabel.isConnected).toBe(false);
    expect(newLabel).not.toBe(oldLabel);
    expect(document.activeElement).toBe(newLabel);
    expect(newLabel.closest<HTMLElement>(".gitRef")!.dataset.name).toBe("feature");
    expect(posts()).toEqual([]);
  });

  it("restores only the latest ticket across two consecutive responses (TC-711)", () => {
    // Case: TC-711 (K22 / A8.3-3)
    focusRow("M");
    const nativeFocus = HTMLElement.prototype.focus;
    const connectedAtCall: boolean[] = [];
    vi.spyOn(HTMLElement.prototype, "focus").mockImplementation(function (
      this: HTMLElement,
      options?: FocusOptions
    ) {
      connectedAtCall.push(this.isConnected);
      nativeFocus.call(this, options);
    });
    loadCommits(standardCommits());
    expect(document.activeElement).toBe(row("M"));
    loadCommits([node("N", ["R"]), node("R", [])]);

    expect(document.activeElement).toBe(row("R"));
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(connectedAtCall.length).toBeGreaterThan(0);
    expect(connectedAtCall.every((connected) => connected)).toBe(true);
  });

  it("does not restore an old-repository ticket after a switch (TC-712)", () => {
    // Case: TC-712 (K22 / A8.3-3)
    focusRow("M");
    dispatch({ command: "selectRepo", repo: OTHER_REPO });
    respondToRefresh(standardCommits(), "R");
    expect(document.activeElement).not.toBe(row("M"));
    expect(rowsWithTabStop()).toEqual(["R"]);

    focusRow("M");
    loadRepos([REPO], REPO);
    respondToRefresh(standardCommits(), "N");
    expect(document.activeElement).not.toBe(row("M"));
    expect(rowsWithTabStop()).toEqual(["N"]);
  });

  it("parks on the list container while loading and resolves the key afterwards (TC-713)", () => {
    // Case: TC-713 (A8.3-5)
    focusRow("M");
    press(row("M"), "r", { ctrlKey: true });
    expect(document.activeElement).toBe(table());
    respondToRefresh(standardCommits());
    expect(document.activeElement).toBe(row("M"));

    press(row("M"), "r", { ctrlKey: true });
    expect(document.activeElement).toBe(table());
    respondToRefresh([node("N", ["R"]), node("R", [])]);
    expect(document.activeElement).toBe(row("R"));
    expect(rowsWithTabStop()).toEqual(["R"]);
  });

  it("keeps the menu and its action context through a same-repository loading view (TC-714)", () => {
    // Case: TC-714 (R4.7); a response with changes still closes it through the existing callback
    fire(row("M"), "contextmenu");
    expect(menuIsActive()).toBe(true);
    focusRow("M");
    press(row("M"), "r", { ctrlKey: true });

    expect(document.getElementById("loadingHeader")).not.toBeNull();
    expect(menuIsActive()).toBe(true);
    clearPosts();
    fire(menuItem(COPY_HASH_TITLE), "click");
    expect(posts("copyToClipboard")).toEqual([expect.objectContaining({ data: "M" })]);
    respondToRefresh(standardCommits());
  });

  it("closes the menu on a repository change and runs nothing from stale items (TC-715)", () => {
    // Case: TC-715 (K31 / A8.3-5)
    fire(row("M"), "contextmenu");
    const staleItem = menuItem(COPY_HASH_TITLE);
    dispatch({ command: "selectRepo", repo: OTHER_REPO });
    expect(menuIsActive()).toBe(false);
    clearPosts();
    fire(staleItem, "click");

    expect(posts("copyToClipboard")).toEqual([]);
    respondToRefresh(standardCommits(), "R");
  });

  it("keeps the menu's hash when the same repository replaces the rows (TC-716)", () => {
    // Case: TC-716 (K46 / A8.3-5)
    fire(row("M"), "contextmenu");
    focusRow("R");
    loadCommits([node("R", []), node("M", ["R"]), node("N", ["M"])]);
    expect(rowsWithTabStop()).toEqual(["R"]);
    expect(menuIsActive()).toBe(true);
    clearPosts();

    fire(menuItem(COPY_HASH_TITLE), "click");

    expect(posts("copyToClipboard")).toEqual([expect.objectContaining({ data: "M" })]);
  });

  it("returns focus to the origin row when details are closed from inside them (TC-719)", () => {
    // Case: TC-719 (A8.3-5; file keys arrive with Task 8, the details row key resolves meanwhile)
    openDetails("N");
    const link = details()!.querySelector<HTMLElement>("a[href]")!;
    link.focus();
    expect(document.activeElement).toBe(link);
    clearPosts();

    respondDetails("N", [], []);

    expect(document.activeElement).toBe(row("N"));
    expect(posts()).toEqual([]);
  });
});

/* ------------------------------------------------------------------ */
/* S75: ref label Enter / Space                                       */
/* ------------------------------------------------------------------ */

// @see docs/testing/perspectives/web/main-test/13-keyboard-accessibility-02.md
describe("ref label Enter / Space open the menu while dblclick keeps the checkout (S75)", () => {
  it("opens the label's menu on Enter and Space without checking out or opening details (TC-726)", () => {
    // Case: TC-726 (R4.3)
    const [featureLabel, hotfixLabel] = labelsOf("M");
    expect(featureLabel.tagName).toBe("BUTTON");
    expect(featureLabel.getAttribute("type")).toBe("button");

    featureLabel.focus();
    const enter = press(featureLabel, "Enter");
    expect(enter.defaultPrevented).toBe(true);
    expect(menuIsActive()).toBe(true);
    expect(posts()).toEqual([]);
    expect(details()).toBeNull();
    fire(document, "click");
    expect(menuIsActive()).toBe(false);

    featureLabel.focus();
    const space = press(featureLabel, " ");
    expect(space.defaultPrevented).toBe(true);
    expect(menuIsActive()).toBe(true);
    expect(posts()).toEqual([]);
    expect(details()).toBeNull();
    fire(document, "click");

    fire(hotfixLabel, "dblclick");
    expect(posts("checkoutBranch")).toEqual([
      { command: "checkoutBranch", repo: REPO, branchName: "hotfix", remoteBranch: null }
    ]);
    expect(details()).toBeNull();
  });

  it("ignores repeated and released Enter on a label (TC-726)", () => {
    // Case: TC-726 (R4.6 guard on the label's own Enter)
    const [label] = labelsOf("M");
    label.focus();
    const repeat = press(label, "Enter", { repeat: true, keyup: false });
    // The shared guard suppresses the native click of a repeated action key on a button.
    expect(repeat.defaultPrevented).toBe(true);
    expect(menuIsActive()).toBe(false);
    label.dispatchEvent(
      new KeyboardEvent("keyup", { key: "Enter", bubbles: true, cancelable: true })
    );
    expect(menuIsActive()).toBe(false);
    expect(posts()).toEqual([]);
  });
});
