import { vi } from "vitest";

vi.stubGlobal(
  "acquireVsCodeApi",
  vi.fn(() => ({
    getState: vi.fn(() => null),
    postMessage: vi.fn(),
    setState: vi.fn()
  }))
);

vi.stubGlobal("webviewLocale", "en");
vi.stubGlobal("webviewMessages", {
  "commitDetails.author": "Author:",
  "commitDetails.commit": "Commit:",
  "commitDetails.committer": "Committer:",
  "commitDetails.date": "Date:",
  "commitDetails.displayingChanges": "Displaying all changes from {0} to {1}.",
  "commitDetails.file.one": "file",
  "commitDetails.file.other": "files",
  "commitDetails.label": "Commit Details",
  "commitDetails.none": "None",
  "commitDetails.parents": "Parents:",
  "commitDetails.uncommittedChanges": "Uncommitted Changes",
  "commitOrdering.authorDate": "Author Date",
  "commitOrdering.date": "Date",
  "commitOrdering.default": "Default",
  "commitOrdering.topological": "Topological",
  "context.copyCommitHash": "Copy Commit Hash to Clipboard",
  "context.copyToClipboard": "Copy {0} to Clipboard",
  "context.more": "More...",
  "context.openFile": "Open File",
  "context.recent": "Recent",
  "date.month.short.0": "Jan",
  "date.month.short.1": "Feb",
  "date.month.short.2": "Mar",
  "date.month.short.3": "Apr",
  "date.month.short.4": "May",
  "date.month.short.5": "Jun",
  "date.month.short.6": "Jul",
  "date.month.short.7": "Aug",
  "date.month.short.8": "Sep",
  "date.month.short.9": "Oct",
  "date.month.short.10": "Nov",
  "date.month.short.11": "Dec",
  "date.relative.day.one": "{0} day ago",
  "date.relative.day.other": "{0} days ago",
  "date.relative.hour.one": "{0} hour ago",
  "date.relative.hour.other": "{0} hours ago",
  "date.relative.minute.one": "{0} minute ago",
  "date.relative.minute.other": "{0} minutes ago",
  "date.relative.month.one": "{0} month ago",
  "date.relative.month.other": "{0} months ago",
  "date.relative.second.one": "{0} second ago",
  "date.relative.second.other": "{0} seconds ago",
  "date.relative.week.one": "{0} week ago",
  "date.relative.week.other": "{0} weeks ago",
  "date.relative.year.one": "{0} year ago",
  "date.relative.year.other": "{0} years ago",
  "dialog.cancel": "Cancel",
  "dialog.dismiss": "Dismiss",
  "dialog.error": "Error:",
  "dialog.no": "No",
  "dialog.validation.invalidCharacters": "Unable to {0}, one or more invalid characters entered.",
  "dialog.yes": "Yes",
  "dropdown.apply": "Apply",
  "dropdown.cancel": "Cancel",
  "dropdown.filter": "Filter {0}...",
  "dropdown.noResults": "No results found.",
  "dropdown.selected": "{0} selected",
  "error.addTag": "Unable to Add Tag",
  "error.applyStash": "Unable to Apply Stash",
  "error.branchFromStash": "Unable to Create Branch from Stash",
  "error.checkoutBranch": "Unable to Checkout Branch",
  "error.checkoutCommit": "Unable to Checkout Commit",
  "error.cherrypickCommit": "Unable to Cherry Pick Commit",
  "error.cleanUntrackedFiles": "Unable to Clean Untracked Files",
  "error.commitDetails": "Unable to load commit details",
  "error.compareCommits": "Unable to load commit comparison",
  "error.copyToClipboard": "Unable to Copy {0} to Clipboard",
  "error.createBranch": "Unable to Create Branch",
  "error.createWorktree": "Unable to Create Worktree",
  "error.pull": "Unable to Pull",
  "error.push": "Unable to Push",
  "error.deleteBranch": "Unable to Delete Branch",
  "error.deleteRemoteBranch": "Unable to Delete Remote Branch",
  "error.deleteTag": "Unable to Delete Tag",
  "error.dropStash": "Unable to Drop Stash",
  "error.fetch": "Unable to Fetch",
  "error.mergeBranch": "Unable to Merge Branch",
  "error.mergeCommit": "Unable to Merge Commit",
  "error.openFile": "Unable to open file",
  "error.openWorktreeInNewWindow": "Unable to Open Worktree in New Window",
  "error.popStash": "Unable to Pop Stash",
  "error.pushStash": "Unable to Stash Changes",
  "error.pushTag": "Unable to Push Tag",
  "error.rebaseBranch": "Unable to Rebase Branch",
  "error.removeWorktree": "Unable to Remove Worktree",
  "error.renameBranch": "Unable to Rename Branch",
  "error.resetToCommit": "Unable to Reset to Commit",
  "error.resetUncommitted": "Unable to Reset Uncommitted Changes",
  "error.revealWorktreeInOS": "Unable to Reveal Worktree in File Manager",
  "error.revertCommit": "Unable to Revert Commit",
  "error.viewDiff": "Unable to view diff of file",
  "file.addition.one": "{0} addition",
  "file.addition.other": "{0} additions",
  "file.binaryTitle": "This is a binary file, unable to view diff.",
  "file.deletion.one": "{0} deletion",
  "file.deletion.other": "{0} deletions",
  "file.renamed": "{0} was renamed to {1}",
  "find.close": "Close (Escape)",
  "find.matchCase": "Match Case",
  "find.next": "Next match (Enter)",
  "find.noResults": "No Results",
  "find.openCommitDetails": "Open the Commit Details View for the current match",
  "find.placeholder": "Find",
  "find.position": "{0} of {1}",
  "find.previous": "Previous match (Shift+Enter)",
  "find.useRegex": "Use Regular Expression",
  "find.zeroLengthRegex": "Cannot use a regular expression which has zero length matches",
  "loading.commitDetails": "Loading {0} ...",
  "loading.label": "Loading ...",
  "table.author": "Author",
  "table.commit": "Commit",
  "table.date": "Date",
  "table.description": "Description",
  "table.graph": "Graph",
  "table.loadMoreCommits": "Load More Commits",
  "toolbar.allAuthors": "All Authors",
  "toolbar.authors": "Authors",
  "toolbar.branches": "Branches",
  "toolbar.repos": "Repos",
  "toolbar.showAll": "Show All",
  "toolbar.switchToListView": "Switch to List View",
  "toolbar.switchToTreeView": "Switch to Tree View"
});
